### ISSUE TITLE
warning during build

### ISSUE THREAD

**Issue by shriram** [brownplt/code.pyret.org#328]
Not sure if this concerns you; FYI:

```
> code.pyret.org@0.0.0 local-install /Users/sk/Desktop/r/code.pyret.org
> heroku local:run npm install

[OKAY] Loaded ENV .env File as KEY=VALUE Format
(node:8942) Warning: a promise was created in a handler at usr/local/lib/node_modules/npm/node_modules/cacache/get.js:159:12 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/method.js:29:9)
```

Also

```
found 522 vulnerabilities (489 low, 27 moderate, 6 high)
```
`npm audit fix` was able to fix some of them but not all. Rerunning local-install ended with 
```
found 37 vulnerabilities (18 low, 16 moderate, 3 high)
```

**Comment by blerner** [comment]
I think is safely closable.  We've fixed basically all the `npm audit` issues, and that particular warning isn't in our code.
